- hosts: localhost
  vars_files:
  - group_vars/dev-vpc
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
  roles:
  - dev-vpc